# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-19 04:51
from __future__ import unicode_literals

import Slamapp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('slug', models.SlugField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('post_feed', models.ImageField(blank=True, null=True, upload_to=Slamapp.models.PathAndRename('posts'))),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('profile_link', models.SlugField(max_length=255, unique=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=Slamapp.models.PathAndRename('profile_photoes'))),
                ('birth_date', models.DateTimeField()),
                ('insta_profile', models.SlugField(max_length=255, unique=True)),
                ('facebook_profile', models.SlugField(max_length=255, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Slamapp.Profile'),
        ),
    ]
